"""add role to users and user_id to tasks

Revision ID: 725c43ce76c9
Revises: 30d2859ed2c8
Create Date: 2026-08-04 17:12:43.257049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725c43ce76c9'
down_revision: Union[str, Sequence[str], None] = '30d2859ed2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
